/* 
  *   Speech.java generated by speechmod 
 */
package Modalities;

import scxmlgen.interfaces.IModality;


public enum Gestures implements IModality{

	// ----------------Complementar----------------
	DELETE("[GESTURES][DELETE]", 1500),

	// ----------------Redundante----------------
	SCROLL_UP("[GESTURES][SCROLL_UP]", 1500),
    SCROLL_DOWN("[GESTURES][SCROLL_DOWN]", 1500),
	GO_BACK("[GESTURES][GO_BACK]", 1500),
	MAIN_PAGE("[GESTURES][MAIN_PAGE]", 1500),

    // ----------------Single----------------
	GO_UP("[GESTURES][GO_UP]", 1500),
	GO_DOWN("[GESTURES][GO_DOWN]", 1500),
	GO_LEFT("[GESTURES][GO_LEFT]", 1500),
	GO_RIGHT("[GESTURES][GO_RIGHT]", 1500),
	CLOSE_WEB("[GESTURES][CLOSE_WEB]", 1500),
    ;

    
    private String event;
    private int timeout;


    Gestures(String m, int time) {
        event=m;
        timeout=time;
    }

    @Override
    public int getTimeOut() {
        return timeout;
    }

    @Override
    public String getEventName() {
        //return getModalityName()+"."+event;
        return event;
    }

    @Override
    public String getEvName() {
        return getModalityName().toLowerCase()+event.toLowerCase();
    }
    
}