/* 
  *   Speech.java generated by speechmod 
 */
package Modalities;

import scxmlgen.interfaces.IModality;


public enum Gestures implements IModality{

	// ----------------Complementar----------------
	REMOVE("[GESTURES][EX]", 5000),

	// ----------------Redundante----------------
	SCROLL_UP("[GESTURES][SCROLLUP]", 5000),
    SCROLL_DOWN("[GESTURES][SCROLLDOWN]", 5000),
	GO_BACK("[GESTURES][GOBACK]", 5000),
	MAIN_PAGE("[GESTURES][MAINPAGE]", 5000),

    // ----------------Single----------------
	GO_UP("[GESTURES][GOUP]", 5000),
	GO_DOWN("[GESTURES][GODOWN]", 5000),
	GO_LEFT("[GESTURES][GOLEFT]", 5000),
	GO_RIGHT("[GESTURES][GORIGHT]", 5000),
	CLOSE_WEB("[GESTURES][EXIT]", 5000),
    SELECT("[GESTURES][SELECT]", 5000),
    ;

    
    private String event;
    private int timeout;


    Gestures(String m, int time) {
        event=m;
        timeout=time;
    }

    @Override
    public int getTimeOut() {
        return timeout;
    }

    @Override
    public String getEventName() {
        //return getModalityName()+"."+event;
        return event;
    }

    @Override
    public String getEvName() {
        return getModalityName().toLowerCase()+event.toLowerCase();
    }
    
}