package Modalities;

import scxmlgen.interfaces.IOutput;

public enum Output implements IOutput{

    OPEN_WEBSITE("[FUSION][OPEN_WEBSITE]"),
    ADD_PRODUCT_CART("[FUSION][ADD_PRODUCT_CART]"),
    ADD_PRODUCT_FAVORITES("[FUSION][ADD_PRODUCT_FAVORITES]"),
    REMOVE_PRODUCT_CART("[FUSION][REMOVE_PRODUCT_CART]"),
    REMOVE_PRODUCT_FAVORITES("[FUSION][REMOVE_PRODUCT_FAVORITES]"),
    SHOW_MORE("[FUSION][SHOW_MORE]"),
    
    SEARCH_PRODUCT_CAMAS("[FUSION][SHOW_PRODUCTS][CAMAS]"),
    SEARCH_PRODUCT_CADEIRAS("[FUSION][SHOW_PRODUCTS][CADEIRAS]"),
    SEARCH_PRODUCT_ARMARIOS("[FUSION][SHOW_PRODUCTS][ARMARIOS]"),
    SEARCH_PRODUCT_ESTANTES("[FUSION][SHOW_PRODUCTS][ESTANTES]"),
    SEARCH_PRODUCT_SOFAS("[FUSION][SHOW_PRODUCTS][SOFAS]"),
    SEARCH_PRODUCT_MESAS("[FUSION][SHOW_PRODUCTS][MESAS]"),


    SCROLL_UP("[FUSION][SCROLL_UP]"),
	SCROLL_DOWN("[FUSION][SCROLL_DOWN]"),
	GO_BACK("[FUSION][GO_BACK]"),
	MAIN_PAGE("[FUSION][MAIN_PAGE]"),
	CLOSE_WEB("[FUSION][CLOSE_WEB]"),
	GO_UP("[FUSION][GO_UP]"),
	GO_DOWN("[FUSION][GO_DOWN]"),
    GO_LEFT("[FUSION][GO_LEFT]"),
	GO_RIGHT("[FUSION][GO_RIGHT]"),
    ;
    
    
    private String event;

    Output(String m) {
        event=m;
    }
    
    public String getEvent(){
        return this.toString();
    }

    public String getEventName(){
        return event;
    }
}
