package Modalities;

import scxmlgen.interfaces.IOutput;

public enum Output implements IOutput{

    OPEN_WEBSITE("[SPEECH][OPEN_WEBSITE]"),
    SHOW_FAVORITES("[SPEECH][SHOW_FAVORITES]"),
    SHOW_CART("[SPEECH][SHOW_CART]"),
    ADD_PRODUCT_CART("[SPEECH][ADD_PRODUCT_CART]"),
    ADD_PRODUCT_FAVORITES("[SPEECH][ADD_PRODUCT_FAVORITES]"),
    REMOVE_PRODUCT_CART("[SPEECH][REMOVE_PRODUCT_CART]"),
    REMOVE_PRODUCT_FAVORITES("[SPEECH][REMOVE_PRODUCT_FAVORITES]"),
    SHOW_MORE("[SPEECH][SHOW_MORE]"),
    
    SEARCH_PRODUCT_CAMAS("[SPEECH][SHOW_PRODUCTS][CAMAS]"),
    SEARCH_PRODUCT_CADEIRAS("[SPEECH][SHOW_PRODUCTS][CADEIRAS]"),
    SEARCH_PRODUCT_ARMARIOS("[SPEECH][SHOW_PRODUCTS][ARMARIOS]"),
    SEARCH_PRODUCT_ESTANTES("[SPEECH][SHOW_PRODUCTS][ESTANTES]"),
    SEARCH_PRODUCT_SOFAS("[SPEECH][SHOW_PRODUCTS][SOFAS]"),
    SEARCH_PRODUCT_MESAS("[SPEECH][SHOW_PRODUCTS][MESAS]"),


    SCROLL_UP("[SPEECH][SCROLL_UP]"),
	SCROLL_DOWN("[SPEECH][SCROLL_DOWN]"),
	GO_BACK("[SPEECH][GO_BACK]"),
	MAIN_PAGE("[SPEECH][MAIN_PAGE]"),
	CLOSE_WEB("[SPEECH][CLOSE_WEB]"),

	GO_UP("[GESTURES][GO_UP]"),
	GO_DOWN("[GESTURES][GO_DOWN]"),
    GO_LEFT("[GESTURES][GO_LEFT]"),
	GO_RIGHT("[GESTURES][GO_RIGHT]"),
    ;
    
    
    private String event;

    Output(String m) {
        event=m;
    }
    
    public String getEvent(){
        return this.toString();
    }

    public String getEventName(){
        return event;
    }
}
