package Modalities;

import scxmlgen.interfaces.IOutput;

public enum Output implements IOutput{

    OPEN_WEBSITE("[SPEECH][OPEN_WEBSITE]"),
    SHOW_FAVORITES("[SPEECH][SHOW_FAVORITES]"),
    SHOW_CART("[SPEECH][SHOW_CART]"),
    ADD_TO_CART("[SPEECH][ADD_TO_CART]"),
    ADD_TO_FAVORITES("[SPEECH][ADD_TO_FAVORITES]"),
    SHOW_MORE("[SPEECH][SHOW_MORE]"),
    
    SEARCH_PRODUCT_CAMAS("[SPEECH][SHOW_PRODUCTS][CAMAS]"),
    SEARCH_PRODUCT_CADEIRAS("[SPEECH][SHOW_PRODUCTS][CADEIRAS]"),
    SEARCH_PRODUCT_ARMARIOS("[SPEECH][SHOW_PRODUCTS][ARMARIOS]"),
    SEARCH_PRODUCT_ESTANTES("[SPEECH][SHOW_PRODUCTS][ESTANTES]"),
    SEARCH_PRODUCT_SOFAS("[SPEECH][SHOW_PRODUCTS][SOFAS]"),
    SEARCH_PRODUCT_MESAS("[SPEECH][SHOW_PRODUCTS][MESAS]"),

    SELECT_PRODUCT_BY_POSITION_1("[SPEECH][SELECT_PRODUCT_BY_POSITION][1]"),
    SELECT_PRODUCT_BY_POSITION_2("[SPEECH][SELECT_PRODUCT_BY_POSITION][2]"),
    SELECT_PRODUCT_BY_POSITION_3("[SPEECH][SELECT_PRODUCT_BY_POSITION][3]"),
    SELECT_PRODUCT_BY_POSITION_4("[SPEECH][SELECT_PRODUCT_BY_POSITION][4]"),
    SELECT_PRODUCT_BY_POSITION_5("[SPEECH][SELECT_PRODUCT_BY_POSITION][5]"),
    SELECT_PRODUCT_BY_POSITION_6("[SPEECH][SELECT_PRODUCT_BY_POSITION][6]"),
    SELECT_PRODUCT_BY_POSITION_7("[SPEECH][SELECT_PRODUCT_BY_POSITION][7]"),
    SELECT_PRODUCT_BY_POSITION_8("[SPEECH][SELECT_PRODUCT_BY_POSITION][8]"),
    SELECT_PRODUCT_BY_POSITION_9("[SPEECH][SELECT_PRODUCT_BY_POSITION][9]"),
    SELECT_PRODUCT_BY_POSITION_10("[SPEECH][SELECT_PRODUCT_BY_POSITION][10]"),

    FINALIZE_ORDER("[SPEECH][FINALIZE_ORDER]"),

    AFFIRM("[SPEECH][AFFIRM]"),
    DENY("[SPEECH][DENY]"),

    SCROLL_UP("[FUSION][SCROLL_UP]"),
	SCROLL_DOWN("[FUSION][SCROLL_DOWN]"),
	GO_BACK("[FUSION][GO_BACK]"),
	MAIN_PAGE("[FUSION][MAIN_PAGE]"),
    REMOVE_PRODUCT_CART("[FUSION][REMOVE_PRODUCT_CART]"),
    REMOVE_PRODUCT_FAVORITES("[FUSION][REMOVE_PRODUCT_FAVORITES]"),
    SELECT("[FUSION][SELECT]"),

	GO_UP("[GESTURES][GO_UP]"),
	GO_DOWN("[GESTURES][GO_DOWN]"),
    GO_LEFT("[GESTURES][GO_LEFT]"),
	GO_RIGHT("[GESTURES][GO_RIGHT]"),
	CLOSE_WEB("[GESTURES][EXIT]"),
    ;
    

    private String event;

    Output(String m) {
        event=m;
    }
    
    public String getEvent(){
        return this.toString();
    }

    public String getEventName(){
        return event;
    }
}
